# Generated by Django 5.1.6 on 2025-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Guia_de_transporte', '0001_initial'), ('Guia_de_transporte', '0002_alter_guiadetransporte_table'), ('Guia_de_transporte', '0003_remove_guiadetransporte_peso_guiadetransporte_notas_and_more'), ('Guia_de_transporte', '0004_alter_guiadetransporte_notas_and_more'), ('Guia_de_transporte', '0005_alter_guiadetransporte_notas'), ('Guia_de_transporte', '0006_add_em_falta_total')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaDeTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(default=0)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guia de Transporte',
                'verbose_name_plural': 'Guias de Transporte',
            },
        ),
        migrations.AlterModelTable(
            name='guiadetransporte',
            table='guia_de_transporte_guiadetransporte',
        ),
        migrations.RemoveField(
            model_name='guiadetransporte',
            name='peso',
        ),
        migrations.AlterField(
            model_name='guiadetransporte',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guiadetransporte',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='guiadetransporte',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guiadetransporte',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
