# Generated by Django 5.1.5 on 2025-02-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guia_de_transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guiadetransporte',
            table='guia_de_transporte_guiadetransporte',
        ),
    ]
