# Generated by Django 5.1.5 on 2025-03-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guia_de_transporte', '0002_alter_guiadetransporte_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiadetransporte',
            name='peso',
        ),
        migrations.AddField(
            model_name='guiadetransporte',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guiadetransporte',
            name='volume',
            field=models.TextField(blank=True),
        ),
    ]
