# Generated by Django 5.1.5 on 2025-03-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guia_de_transporte', '0003_remove_guiadetransporte_peso_guiadetransporte_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadetransporte',
            name='notas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guiadetransporte',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guiadetransporte',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
