# Generated by Django 5.1.5 on 2025-03-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guia_de_transporte', '0004_alter_guiadetransporte_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadetransporte',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
