# Generated by Django 4.2.20 on 2025-03-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guia_de_transporte', '0008_remove_guiadetransporte_unidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('unidade', models.CharField(default='UN', max_length=50)),
                ('quantidade', models.IntegerField(default=0)),
                ('em_falta', models.CharField(default='0', max_length=50)),
                ('total', models.CharField(default='0', max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('imagem', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='guiadetransporte',
            name='imagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guiadetransporte',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='guiadetransporte',
            name='unidade',
            field=models.CharField(default='UN', max_length=50),
        ),
        migrations.AddField(
            model_name='guiadetransporte',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
