# Generated by Django 4.2.20 on 2025-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guia_de_transporte', '0009_transportitem_guiadetransporte_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiadetransporte',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
