# Generated by Django 4.2.20 on 2025-03-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guia_de_transporte', '0010_guiadetransporte_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiadetransporte',
            name='current_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportitem',
            name='current_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
