# Generated by Django 5.1.5 on 2025-01-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=255)),
                ('instalacao', models.CharField(max_length=255)),
                ('codigos_da_porta', models.TextField()),
                ('codigo_caves', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['localizacao'],
            },
        ),
    ]
