# Generated by Django 5.1.5 on 2025-01-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(help_text='Descrição do local (pode haver várias instalações no mesmo local).', max_length=255)),
                ('instalacao', models.CharField(help_text="Nome único ou identificador da instalação (ex: 'Sala 101').", max_length=255, unique=True)),
                ('codigos_da_porta', models.TextField(help_text='Códigos de acesso à porta, separados por vírgula.')),
                ('codigo_caves', models.CharField(help_text="Código adicional (por exemplo, 'caves').", max_length=255)),
                ('local_da_chave', models.CharField(blank=True, default='', help_text='Localização da chave', max_length=255)),
                ('administracao', models.CharField(blank=True, default='', help_text='Informação sobre administração', max_length=255)),
                ('tipo_de_contrato', models.CharField(blank=True, default='', help_text='Tipo do contrato', max_length=255)),
            ],
            options={
                'ordering': ['localizacao'],
            },
        ),
    ]
