# Generated by Django 5.1.5 on 2025-01-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codigoentrada',
            unique_together={('localizacao', 'instalacao')},
        ),
    ]
