# Generated by Django 5.1.5 on 2025-01-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoentrada',
            name='local_de_chaves',
            field=models.CharField(blank=True, help_text='Localização das chaves', max_length=255, null=True),
        ),
    ]
