# Generated by Django 5.1.5 on 2025-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoentrada',
            name='instalacao',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
