# Generated by Django 5.1.5 on 2025-01-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0002_alter_codigoentrada_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoentrada',
            name='codigos_da_porta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
