# Generated by Django 5.1.5 on 2025-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0002_alter_codigoentrada_local_de_chaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoentrada',
            name='administracao',
            field=models.CharField(blank=True, default='', help_text='Informação sobre administração', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='codigo_caves',
            field=models.CharField(blank=True, help_text="Código adicional (por exemplo, 'caves').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='codigos_da_porta',
            field=models.TextField(blank=True, help_text='Códigos de acesso à porta, separados por vírgula.', null=True),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='tipo_de_contrato',
            field=models.CharField(blank=True, default='', help_text='Tipo do contrato', max_length=255, null=True),
        ),
    ]
