# Generated by Django 5.1.5 on 2025-01-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0002_alter_codigoentrada_instalacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoentrada',
            name='codigo_caves',
            field=models.CharField(help_text="Código adicional (por exemplo, 'caves').", max_length=255),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='codigos_da_porta',
            field=models.TextField(help_text='Códigos de acesso à porta, separados por vírgula.'),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='instalacao',
            field=models.CharField(help_text='Nome único ou identificador da instalação (ex: Sala 101).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='localizacao',
            field=models.CharField(help_text='Descrição do local (pode haver várias instalações no mesmo local).', max_length=255),
        ),
    ]
