# Generated by Django 4.2.20 on 2025-03-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0003_alter_codigoentrada_administracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoentrada',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Flag para exclusão lógica'),
        ),
    ]
