# Generated by Django 5.1.5 on 2025-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0003_alter_codigoentrada_codigo_caves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoentrada',
            name='instalacao',
            field=models.CharField(help_text="Nome ou identificador da instalação (ex: 'Sala 101').", max_length=255),
        ),
    ]
