# Generated by Django 5.1.5 on 2025-01-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0004_alter_codigoentrada_instalacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoentrada',
            name='administracao',
            field=models.CharField(default='Desconhecido', help_text='Informações sobre a administração responsável.', max_length=255),
        ),
        migrations.AddField(
            model_name='codigoentrada',
            name='local_de_chaves',
            field=models.CharField(default='Desconhecido', help_text='Local onde as chaves estão armazenadas.', max_length=255),
        ),
        migrations.AddField(
            model_name='codigoentrada',
            name='tipo_de_contrato',
            field=models.CharField(default='Desconhecido', help_text='Tipo de contrato associado à instalação.', max_length=255),
        ),
        migrations.AlterField(
        model_name='codigoentrada',
        name='instalacao',
        field=models.CharField(help_text="Nome único ou identificador da instalação (ex: 'Sala 101').", max_length=255),
        ),

    ]
