# Generated by Django 5.1.5 on 2025-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0007_merge_20250123_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoentrada',
            name='novo_campo',
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='administracao',
            field=models.CharField(help_text='Informações sobre a administração responsável.', max_length=255),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='instalacao',
            field=models.CharField(help_text="Nome único ou identificador da instalação (ex: 'Sala 101').", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='local_de_chaves',
            field=models.CharField(help_text='Local onde as chaves estão armazenadas.', max_length=255),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='tipo_de_contrato',
            field=models.CharField(help_text='Tipo de contrato associado à instalação.', max_length=255),
        ),
    ]
