# Generated by Django 5.1.5 on 2025-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_do_app', '0007_merge_20250123_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoentrada',
            name='novo_campo',
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='administracao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='codigo_caves',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='codigos_da_porta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='instalacao',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='local_de_chaves',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='localizacao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codigoentrada',
            name='tipo_de_contrato',
            field=models.CharField(max_length=255),
        ),
    ]
