# Generated by Django 4.2.20 on 2025-03-28 21:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaCarro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_combustivel', models.CharField(max_length=50)),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_despesa', models.DateField()),
                ('quilometragem', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('imagem', models.TextField(blank=True, null=True)),
                ('imagens', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario_criacao', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_carro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa de Carro',
                'verbose_name_plural': 'Despesas de Carro',
                'ordering': ['-data_despesa'],
            },
        ),
    ]
