# Generated by Django 5.1.5 on 2025-01-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_instalacao', models.CharField(max_length=100)),
                ('pergunta_id', models.IntegerField()),
                ('resposta', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('tecnico', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
