# Generated by Django 5.1.5 on 2025-01-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
