# Generated by Django 5.1.5 on 2025-01-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_resposta_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['numero_instalacao', 'pergunta_id']},
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together={('numero_instalacao', 'pergunta_id')},
        ),
    ]
