# Generated by Django 5.1.6 on 2025-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guia_de_transporte', '0007_fix_migration_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiadetransporte',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='guiadetransporte',
            name='volume',
        ),
        migrations.AddField(
            model_name='guiadetransporte',
            name='em_falta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guiadetransporte',
            name='total',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
