# Generated by Django 5.1.5 on 2025-02-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=255)),
                ('instalacao', models.CharField(max_length=255)),
                ('descricao_da_avaria', models.TextField(blank=True, null=True)),
                ('data_da_avaria', models.CharField(max_length=255)),
                ('fim_da_avaria', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_do_elevador', models.CharField(max_length=255)),
                ('pago', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3)),
                ('notas', models.TextField(blank=True, null=True)),
                ('codigo_material', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_material', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
