# Generated by Django 5.1.5 on 2025-02-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias_a_receber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
