# Generated by Django 5.1.5 on 2025-02-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias_a_receber', '0002_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='fim_deslocacao1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avaria',
            name='fim_deslocacao2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avaria',
            name='inicio_deslocacao1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avaria',
            name='inicio_deslocacao2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
