# Generated by Django 4.2.20 on 2025-03-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias_a_receber', '0003_avaria_fim_deslocacao1_avaria_fim_deslocacao2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='current_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
