# Generated by Django 4.2.20 on 2025-03-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias_a_receber', '0004_avaria_current_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatesConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=6)),
                ('stop_rate', models.DecimalField(decimal_places=2, default=11.0, max_digits=6)),
                ('after_11pm_surcharge', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('current_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('current_user',)},
            },
        ),
    ]
