# Generated by Django 4.2.20 on 2025-03-26 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registros_de_Entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrega',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='registroentrega',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
