# Generated by Django 4.2.20 on 2025-03-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros_de_Entregas', '0002_registroentrega_data_criacao_registroentrega_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrega',
            name='_imagens',
            field=models.TextField(blank=True, db_column='imagens', null=True, verbose_name='Imagens Adicionais'),
        ),
    ]
