# Generated by Django 4.2.20 on 2025-03-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros_de_Entregas', '0003_registroentrega__imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroentrega',
            name='_imagens',
        ),
        migrations.AddField(
            model_name='registroentrega',
            name='imagens',
            field=models.TextField(blank=True, null=True, verbose_name='Imagens Adicionais'),
        ),
    ]
