# Generated by Django 4.2.20 on 2025-03-26 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registros_de_Entregas', '0004_remove_registroentrega__imagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrega',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
