# Generated by Django 4.2.20 on 2025-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros_de_Entregas', '0005_registroentrega_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrega',
            name='data_entrega_doc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega à Chefia'),
        ),
        migrations.AddField(
            model_name='registroentrega',
            name='data_trabalho_finalizado',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Finalização'),
        ),
    ]
