# Generated by Django 4.2.20 on 2025-04-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros_de_Entregas', '0006_registroentrega_data_entrega_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrega',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('trabalho_directo_faturar', '1. Trabalho Directo a Facturar'), ('trabalho_directo_contrato', '2. Trabalho Directo (Contracto Completo)'), ('obra', '3. Obra'), ('requisicao_material', '4. Requisição de Material'), ('retirada_lixo', '5. Pedido de Retirada de Lixo das Instalações'), ('marcacao_ferias', '6. Marcação de Férias'), ('outros', '7. Outros')], default='trabalho_directo_faturar', max_length=50, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
